# Generated by Django 4.2 on 2023-04-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_admin_remove_payment_received_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='students',
            new_name='student',
        ),
    ]
