# Generated by Django 4.2 on 2023-04-26 08:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_students_applicant_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='day_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma')], size=None, verbose_name='Dars kunlari'),
        ),
    ]
