# Generated by Django 4.2 on 2023-04-26 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_group_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='day_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None, verbose_name='Dars kunlari'),
        ),
    ]
