# Generated by Django 4.2 on 2023-04-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
