# Generated by Django 4.2 on 2023-04-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registered_time',
        ),
        migrations.AddField(
            model_name='student',
            name='start_day',
            field=models.DateField(null=True),
        ),
    ]
