# Generated by Django 4.2 on 2023-04-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_applicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
