# Generated by Django 4.2 on 2023-04-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
