# Generated by Django 4.2 on 2023-05-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_student_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='should_attend',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name="Tug'lgan joy"),
        ),
    ]
