# Generated by Django 4.2 on 2023-05-05 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_boshliq'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.admin'),
        ),
    ]
