# Generated by Django 4.2 on 2023-05-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_payment_group_alter_payment_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
