# Generated by Django 4.2 on 2023-05-10 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0021_remove_attendance_course_attendance_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(choices=[('new_group', 'Yangi guruh ochish kerak'), ('applicant', 'yangi kelganlarga tel qilish kerak'), ('missed_student', 'kelmagan guruhlar tel qilish kerak')], max_length=255)),
                ('ffrom', models.ForeignKey(limit_choices_to={'groups__name__in': ['teacher', 'boshliq']}, on_delete=django.db.models.deletion.CASCADE, related_name='messages_from', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
                ('to', models.ForeignKey(limit_choices_to={'groups__name__in': ['Admin', 'teacher']}, on_delete=django.db.models.deletion.CASCADE, related_name='messages_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
