# Generated by Django 4.2 on 2023-05-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alertmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmessages',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'tugagan'), ('uncompleted', 'tugatmagan')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(choices=[('completed', 'tugagan'), ('uncompleted', 'tugatmagan')], default='uncompleted', verbose_name='status admin'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('completed', 'tugagan'), ('uncompleted', 'tugatmagan')], default='uncompleted', verbose_name='status group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('completed', 'tugagan'), ('uncompleted', 'tugatmagan')], default='uncompleted', verbose_name='status student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('completed', 'tugagan'), ('uncompleted', 'tugatmagan')], default='uncompleted', verbose_name='status teacher'),
        ),
    ]
