# Generated by Django 4.2 on 2023-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alertmessages_status_alter_admin_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmessages',
            name='status',
            field=models.CharField(choices=[('completed', 'tugagan'), ('uncompleted', 'tugatmagan')], default='uncompleted', max_length=255),
        ),
    ]
