# Generated by Django 4.2.7 on 2024-01-02 10:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_student_first_name_alter_student_last_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('confirmed_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
